config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { 
     omniauth_callbacks: 'users/omniauth_callbacks',
     registrations: "users/registrations"
  }
  root to: "tops#index"

  get 'musics/index'
  post 'musics/search'
  get "musics/play"
  get "musics/rest"
  get "musics/history"
  get "musics/how"

  resources :users
  resources :posts
  resources :music_histories, only: %i[create]
  resources :post_favorites, only: %i[create destroy]

  namespace :admin do
    resources :users
  end
end

app/models/post_favorite.rb
class PostFavorite < ApplicationRecord
  
  belongs_to :user
  belongs_to :post

  validates :user_id, :uniqueness => {:scope => :post_id}
  
end

app/controllers/post_favorites_controller.rb
class PostFavoritesController < ApplicationController
  
  def create
    @post = Post.find(params[:post_id])
    current_user.post_favorites.create(post_id: params[:post_id])
      respond_to do |format|
        format.js{render :create}
      end
  end

  def destroy
    @post = Post.find(params[:post_id])
    current_user.post_favorites.find_by(id: params[:id]).destroy
      respond_to do |format|
        format.js{render :destroy}
      end
  end
  
end

app/views/post_favorites/_like.html.erb
<% unless post.user_id == current_user.id %>
  <% post_favorite = current_user.post_favorites.find_by(post_id: post.id) %>
  <% if post_favorite.present? %>
    <%= link_to post_favorite_path(id: post_favorite.id, post_id: post.id), method: :delete, remote: true do %>
      <div class = "iine__button">❤︎<%= post.post_favorites.count %></div>
    <% end %>
    <% else %>
      <%= link_to post_favorites_path(post_id: post.id), method: :post, remote: true do %>
      <div class = "iine__button">♡️<%= post.post_favorites.count %></div>
    <% end %>
  <% end %>
<% end %>

app/views/post_favorites/create.js.erb
$('#likes_buttons_<%= @post.id %>').html("<%= j(render 'post_favorites/like', { post: @post}) %>");

app/views/post_favorites/destroy.js.erb
$('#likes_buttons_<%= @post.id %>').html("<%= j(render 'post_favorites/like', { post: @post}) %>");