config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { 
     omniauth_callbacks: 'users/omniauth_callbacks',
     registrations: "users/registrations"
  }
  root to: "tops#index"

  get 'musics/index'
  post 'musics/search'
  get "musics/play"
  get "musics/rest"
  get "musics/history"
  get "musics/how"

  resources :users
  resources :posts
  resources :music_histories, only: %i[create]
  resources :post_favorites, only: %i[create destroy]

  namespace :admin do
    resources :users
  end
end

app/models/post.rb
class Post < ApplicationRecord
  
  validates :post_image, presence: true, if: -> { content.blank? }
  validates :content, presence: true, if: -> { post_image.blank? }
  validates :content, length: {maximum: 100}

  belongs_to :user
  has_many :post_favorites, dependent: :destroy
  
  mount_uploader :post_image, ImageUploader 
  
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  
  def index
    @posts = Post.page(params[:page]).per(10).order(created_at: :desc)
    @post = Post.new
    respond_to do |format|
      format.js{render :post} 
      format.html
    end
  end

  def create
    @post = current_user.posts.build(set_params)
    @posts = Post.page(params[:page]).per(10).order(created_at: :desc)
    if @post.save
      respond_to do |format|
        format.js{render :index}
      end
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @posts = Post.page(params[:page]).per(10).order(created_at: :desc)
    if @post.destroy
      respond_to do |format|
        format.js{render :index}
      end
    end
  end

  private

  def set_params
    params.require(:post).permit(:content, :post_image, :user_id)
  end
  
end

app/views/posts/_form.html.erb
<%= form_with(model:@post) do |f| %>
  <div class="text-center form_font">
  <% user = User.find_by(id: current_user.id) %>
    <% if user.provider.present? %>
      <%= image_tag user.image_url, size: "100x100", class: "circle_image" if user.image_url %>
    <% end %>
    <% unless user.provider.present? %>  
      <%= image_tag(user.avatar.url,class: "circle_image user_image_size") if user.avatar && user.avatar.url %>
    <% end %>
    <%= f.text_field :content, placeholder: "いまpomoしてる?", class: "form-control-lg" %>
    <div class="text-right post_image">
      <%= f.file_field :post_image, class:"file" %>
      <p class="your_preview">(選択した画像のプレビュー)</p>
      <div class="img_avatar"></div>
    </div>
  </div>

  <div class="actions text-center post_admit">
    <%= f.submit "pomoをつぶやく", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/posts/_index.html.erb
<div class="form_font" id>
<% posts.each do |post| %>
  <div>
    <div>
      <% user = User.find_by(id: post.user_id) %>
      <%= link_to(user_path(user), style: "color:black;")  do %>
        <% if user.provider.present? %>
          <%= image_tag user.image_url, size: "50x50",class: "circle_image" if user.image_url %>
        <% end %>
        <% unless user.provider.present? %>  
          <%= image_tag(user.avatar.url,class: "circle_image") if user.avatar && user.avatar.url %>
        <% end %>
        <span class="post_name"><%= user.name %></span>
      <% end %>
    </div>
    <div class="post_image">
    <%= image_tag(post.post_image.url, class: "post_image_size") if post.post_image && post.post_image.url %>  
    <% if post.post_image && post.post_image_url %>
      <%= link_to "元のサイズで画像を表示する", post.post_image.url, target: "_blank" %>    
    <% end %>
    </div>
    <div class="post_content">
    <%= post.content %>
    </div>
    <div class="post_created_at">
      <em><%= post.created_at.strftime("%Y年%m月%d日　%-H時%-M分%-S秒") %></em>
      &nbsp
      <span id="likes_buttons_<%= post.id %>">
        <%= render partial: 'post_favorites/like', locals: { post: post} %>
      </span>
      <% if current_user.id == post.user_id %>
        <%= link_to "削除する", post_path(post), method: :delete, data: {confirm: "削除して宜しいですか?"}, class: "btn btn-danger", remote: true %>
      <% end %>
    </div>
  </div>
  <hr>
<% end %>
</div>

app/views/posts/index.html.erb
<% provide(:title, "掲示板") %>
<% if @post.errors.any? %>
  <div id="error_explanation">
    <h2><%= @post.errors.count %>件のエラーがあります。</h2>
    <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= render "shared/post_form" %>

<script type="text/javascript">
$(document).on('turbolinks:load', function(){
  $(document).ready(function () {
    let view_box = $('.img_avatar');

    $(".file").on('change', function(){
      let fileprop = $(this).prop('files')[0],
      find_img = $(this).next('img'),
      fileRdr = new FileReader();

      if(find_img.length){
        find_img.nextAll().remove();
        find_img.remove();
      }

      let img = '<img width="100" alt="" class="img_view"><a href="#" class="img_del">プレビューを削除する</a>';
      view_box.append(img);

      fileRdr.onload = function() {    
        view_box.find('img').attr('src', fileRdr.result);
        img_del(view_box); 
      }

      fileRdr.readAsDataURL(fileprop);  

      if($(".img_view").length){
        $(".file").hide();
      }

      $(".your_preview").show();
    });

    function img_del(target){
      target.find("a.img_del").on('click',function(){
        $(this).parent().find('input[type=file]').val('');
        $(this).parent().find('.img_view, br').remove();
        $(this).remove();
        $("#post_post_image").val("");
        $(".file").show();
        $(".your_preview").hide();

        return false;
      });
    }  
  });
});
</script>

app/views/posts/index.js.erb
$("#posts_area").html("<%= j(render 'posts/index', { posts: @posts, post: @post }) %>");
$("#post_content").val('');
$("#post_post_image").val('');
$(".img_view").remove();
$(".img_del").remove();
$(".your_preview").hide();
$(".file").show();

app/views/posts/post.js.erb
$("#posts_area").html("<%= j(render 'posts/index', { posts: @posts, post: @post }) %>");