config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { 
     omniauth_callbacks: 'users/omniauth_callbacks',
     registrations: "users/registrations"
  }
  root to: "tops#index"

  get 'musics/index'
  post 'musics/search'
  get "musics/play"
  get "musics/rest"
  get "musics/history"
  get "musics/how"

  resources :users
  resources :posts
  resources :music_histories, only: %i[create]
  resources :post_favorites, only: %i[create destroy]

  namespace :admin do
    resources :users
  end
end

app/models/music.rb
class Music < ApplicationRecord
  validates :title, uniqueness: true
  
  has_many :music_histories
end

app/controllers/musics_controller.rb
require 'net/http'
require 'uri'
require 'json'
require 'google/apis/youtube_v3'
include MusicService

class MusicsController < ApplicationController
  before_action :authenticate_user!
  
  def index
    @trends = Music.find(Music.pluck(:id).shuffle[0..10])
  end

  def search
    mixcloud_api
    youtube_api
    respond_to do |format|
        format.js{render :index}
    end
  end

  def play
    @title = params[:title]
    @image_url = params[:image_url]
    @music_url = params[:music_url]
  
    create_or_not_musics
    current_user.music_histories.create(music_id: create_or_not_musics)

    @posts = Post.page(params[:page]).per(10).order(created_at: :desc)
    @post = Post.new
  end

  def rest
    @posts = Post.page(params[:page]).per(10).order(created_at: :desc)
    @post = Post.new
    create_or_update_studies
  end

  def how
  end

  def history
    @musics = current_user.music_histories.order(created_at: :desc).page(params[:page]).per(10)
    @created_at = current_user.music_histories.pluck(:created_at).sort!.reverse!
  end
end

app/helpers/musics_helper.rb
module MusicsHelper
  
  def youtube_api
    if params[:q] != ""
        q = params[:q]
        youtube = Google::Apis::YoutubeV3::YouTubeService.new
        youtube.key = ENV['YOUTUBE_KEY']
        youtube_response = youtube.list_searches("id,snippet", type: "video", q: q, max_results: 2)
        @youtube_response = youtube_response.items
    end
  end

  def mixcloud_api
    if params[:q] != ""
      q = params[:q]
      uri = URI.parse URI.encode("https://api.mixcloud.com/search/?q=#{q}&amp;type=cloudcast")
      mixcloud_response = JSON.load(Net::HTTP.get(uri))
      @mixcloud_response = mixcloud_response["data"]
    end
  end

  def create_or_update_studies    
    if Study.where("user_id = ? and start_at = ?", current_user.id, Date.today).present?
      study = Study.where("user_id = ? and start_at = ?", current_user.id, Time.zone.today).first
      study_set = study.set
      study_set += 1 
      study.update_attribute :set, study_set
    else
      study = Study.new(user_id: current_user.id, set: 1, start_at: Date.today)
      study.save!
    end
  end

  def create_or_not_musics
    if Music.where("title = ? ", @title).pluck(:id).present?
      music_id = Music.where("title = ? ", @title).pluck(:id)[0]
    else
      music_id = create_musics
    end
  end

  def create_musics  
    unless Music.where("title = ?", @title).present?
      music = Music.new(title: @title, image_url: @image_url, music_url: @music_url)
      music.save!
      music.id
    end
  end
  
end

app/views/musics/_index.html.erb
<% if mixcloud_response.present? %>
  <div class="row">
    <% mixcloud_response.each do |list| %>
      <div class="col-md-4">
        <div class="music_list">
          <% music_url = "https://www.mixcloud.com/widget/iframe/?feed=#{list['url']}" %>
          <%= link_to(musics_play_path(title: list["name"], image_url: list["pictures"]["large"], music_url: music_url)) do %>
          <div>
            <%= list["name"] %>
          </div>
          <div>
            <img src="<%= list["pictures"]["large"] %>">
          </div>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
<% end %>

<% if youtube_response.present? %>
<div class="row">
  <% youtube_response.each do |list| %>
    <div class="col-md-4">
      <div class="music_list">
        <% music_url = "https://www.youtube.com/embed/#{list.id.video_id}" %>
        <%= link_to(musics_play_path(title: list.snippet.title, image_url: list.snippet.thumbnails.medium.url, music_url: music_url)) do %>
        <div>
          <%= list.snippet.title %>
        </div>
        <div>
          <img src="<%= list.snippet.thumbnails.medium.url %>">
        </div>
        <% end %>
      </div>
    </div>
  <% end %>
</div>
<% end %>

app/views/musics/_mixcloud.html.erb
<% mixcloud_response.each do |list| %>
  <div class="col-md-4">
    <div class="music_list">
      <% music_url = "https://www.mixcloud.com/widget/iframe/?feed=#{list['url']}" %>
      <%= link_to(musics_play_path(title: list["name"], image_url: list["pictures"]["large"], music_url: music_url)) do %>
      <div>
        <%= list["name"] %>
      </div>
      <div>
        <img src="<%= list["pictures"]["large"] %>">
      </div>
      <% end %>
    </div>
  </div>
<% end %>

app/views/musics/_youtube.html.erb
<% youtube_response.each do |list| %>
    <div class="col-md-4">
      <div class="music_list">
        <% music_url = "https://www.youtube.com/embed/#{list.id.video_id}" %>
        <%= link_to(musics_play_path(title: list.snippet.title, image_url: list.snippet.thumbnails.medium.url, music_url: music_url)) do %>
        <div>
          <%= list.snippet.title %>
        </div>
        <div>
          <img src="<%= list.snippet.thumbnails.medium.url %>">
        </div>
        <% end %>
      </div>
    </div>
  <% end %>

app/views/musics/history.html.erb
<% provide(:title, "再生履歴") %>
<% @musics.each do |music|%>    
  <div>
    <%= image_tag music.music[:image_url], size: "80x80" if music.music[:image_url] %>
    <%= music.music[:title] %>
    <%= link_to "  再生する",musics_play_path(title: music.music[:title], image_url: music.music[:image_url], music_url: music.music[:music_url]), class: "fas fa-play-circle btn btn-dark btn-lg" %>
  </div>
  <div>
    <em><%= music.created_at.strftime("再生：%Y年%m月%d日　%-H時%-M分%-S秒") %></em>
  </div>
  <hr>
<% end %>
<%= paginate @musics %>

app/views/musics/how.html.erb
<% provide(:title, "使い方") %>
<div class="how_nav">
  <%= render "shared/how" %>
</div>

app/views/musics/index.html.erb
<% provide(:title, "音楽を検索") %>
<div class="row justify-content-center form_font search_field">
  <div class="col-md-offset-3 col-md-6 col-md-offset-3">
    <%= form_tag(musics_search_path, method: "post", remote: true) do %>
      <div class="field">
        <%= label_tag(:q, "") %>
        <%= text_field_tag :q, nil, placeholder: '聞きたい音楽を検索してpomoしよう',class: "form-control search_form" %>
      </div>
      <div class="search_actions text-center">
        <%= submit_tag "Search", class: "btn btn-dark" %>
      </div>
    <% end %>
  </div>
</div>
<hr>

<h2 class="trend_music">Trend Music</h2>
<div class="row justify-content-center">
  <div class="col-md-offset-1 col-md-10  col-md-offset-1">
    <div class="top_slide">
      <%= render partial: 'trends/trend', collection: @trends %>
    </div>
  </div>
</div>

<div id="mask" class="hidden">
  <section id="modal" class="hidden">
    <%= render "shared/how" %>
    <div id="close">
      閉じる
    </div>
  </section>
</div>
<hr>

<h2 class="search_music">Search Result</h2>
<h4 class="search_music">(検索結果が表示されます)</h4>
<div class="row justify-content-center">
  <div class="col-md-12">
    <div class="col-sm-12 text-center">
      <div id="movies_area">
        <%= render partial: 'index', locals: { youtube_response: @youtube_response, mixcloud_response: @mixcloud_response } %>
      </div>
    </div>
  </div>
</div>


<script type="text/javascript">
document.addEventListener("turbolinks:load",function(){
  $(function(){
    $('.top_slide').slick({
      accessibility: true,
      autoplay: true,
      autoplaySpeed: 2000,
      speed: 3000,
      pauseOnHover: true,
      cssEase: 'ease',
      dots: false,
      infinite: true,
      vertical: false,
      swipe: true,
      slidesToShow: 2,
      slidesToScroll: 2,
      centerMode: true,
      arrows: true,
      prevArrow: '<button class="slide_button slide-arrow prev-arrow"></button>',
      nextArrow: '<button class="slide_button slide-arrow next-arrow"></button>',
      responsive: [
      {
        breakpoint: 1024, 
        settings: {
          slidesToShow:2,
          slidesToScroll: 1,
        }
      }, 
      {
        breakpoint: 768, 
        settings: {
          slidesToShow:1,
          slidesToScroll: 1,
          centerMode: true,
          centerPadding: '10px',
          arrows: false,
        }
      }
      ]
    });
  });
});
</script>

app/views/musics/index.js.erb
$("#movies_area").html("<%= escape_javascript(render partial: 'musics/index', locals: { youtube_response: @youtube_response, mixcloud_response: @mixcloud_response }) %>")

app/views/musics/play.html.erb
<% provide(:title, "集中タイム") %>
<div class="text-center top_clock">
  <div id="timer">25:00</div>
  <div class="play_time">Run Time</div>
</div>
<div class="controls text-center">
  <div id="min" class="btn btn-dark">Min</div>
  <div id="sec" class="btn btn-dark">Sec</div>
  <div id="reset" class="btn btn-danger">Reset</div>
  <div id="start" class="btn btn-primary">Start</div>
</div>
<hr>
<div class="row justify-content-center">
  <div class="col-md-offset-1 col-md-10 col-md-offset-1">
    <h2 class="text-center"><%= @title %></h2>
    <div class="text-center embed-responsive embed-responsive-21by9">
      <iframe class="embed-responsive-item" id='iframe' width="560" height="315" 
        src="<%= @music_url %>"
        frameborder="0" 
        allowfullscreen>
      </iframe>
    </div>
  </div>
</div>
<hr>
<div>
  <%= render "shared/post_form" %>
</div>

<%= audio_tag("alert.mp3", id:"audio") %>

<script type="text/javascript">
document.addEventListener("turbolinks:load", function(){
  let timer = document.getElementById('timer');
  let min = document.getElementById('min');
  let sec = document.getElementById('sec');
  let reset = document.getElementById('reset');
  let start = document.getElementById('start');
  let audio = document.getElementById('audio');
  let iframe = document.getElementById('iframe');
  let startTime;
  let timeLeft;
  let timeToCountDown = 1000 * 60 * 25;
  let timerId;
  let isRunning = false;

  function countDown(){
    timerId = setTimeout(function(){
      timeLeft = timeToCountDown - (Date.now() - startTime);
      if(timeLeft < 0){
        isRunning = false;
        start.textContent = "Start";
        clearTimeout(timerId);
        timeLeft = 0;
        timeToCountDown = 0;
        updateTimer(timeLeft);
        console.log("音楽ストップ");
        iframe.remove();
        location.href="/musics/rest";
        return;
      }
      updateTimer(timeLeft)
      countDown();
    },10);
  }

  function updateTimer(t){
    let d = new Date(t);
    let m = d.getMinutes();
    let s = d.getSeconds();
    m = ('0' + m).slice(-2);
    s = ('0' + s).slice(-2);
    let timerString = m + ":" + s;
    timer.textContent = timerString;
    document.title = timerString;
  }

  start.addEventListener("click", function(){
    if (isRunning === false){
      isRunning = true;      
      start.style.display="none";
      min.style.display="none";
      sec.style.display="none";
      reset.style.display="none";
      startTime = Date.now();
      countDown();
    }else{
      isRunning = false;
      start.textContent = "Start";
      timeToCountDown = timeLeft;
      clearTimeout(timerId);
    }
    setTimeout(function(){
      audio.play();
    }, (timeToCountDown - 6000))
  });

  min.addEventListener("click", function(){
    if (isRunning === true) {
      return;
    }
    timeToCountDown += 60 * 1000;
    if (timeToCountDown >= 60 * 60 * 1000) {
      timeToCountDown = 0;
    }
    updateTimer(timeToCountDown);
  });
  
  sec.addEventListener("click", function(){
    if (isRunning === true) {
      return;
    }
    timeToCountDown += 1000;
    if (timeToCountDown >= 60 * 60 * 1000) {
      timeToCountDown = 0;
    }
    updateTimer(timeToCountDown);
  });

  reset.addEventListener("click", function(){
    timeToCountDown = 0;
    updateTimer(timeToCountDown);
  });
  $(document).ready(function () {
    let view_box = $('.img_avatar');

    $(".file").on('change', function(){
      let fileprop = $(this).prop('files')[0],
      find_img = $(this).next('img'),
      fileRdr = new FileReader();

      if(find_img.length){
        find_img.nextAll().remove();
        find_img.remove();
      }

      let img = '<img width="100" alt="" class="img_view"><a href="#" class="img_del">プレビューを削除する</a>';
      view_box.append(img);

      fileRdr.onload = function() {    
        view_box.find('img').attr('src', fileRdr.result);
        img_del(view_box); 
      }

      fileRdr.readAsDataURL(fileprop);  

      if($(".img_view").length){
        $(".file").hide();
      }

      $(".your_preview").show();
    });

    function img_del(target){
      target.find("a.img_del").on('click',function(){
        $(this).parent().find('input[type=file]').val('');
        $(this).parent().find('.img_view, br').remove();
        $(this).remove();
        $("#post_post_image").val("");
        $(".file").show();
        $(".your_preview").hide();

        return false;
      });
    }  
  });
});
</script>

app/views/musics/rest.html.erb
<% provide(:title, "休憩タイム") %>
<div class="text-center top_clock">
  <div class="rest_timer" id="timer">25:00</div>
  <div class="rest_time">Rest Time</div>
</div>
<%= audio_tag("alert.mp3", id:"audio") %>
<hr>
<div>
  <%= render "shared/post_form" %>
</div>

<script type="text/javascript">
document.addEventListener("turbolinks:load", function(){
  let timer = document.getElementById('timer');
  let startTime;
  let timeLeft;
  let timeToCountDown = 1000 * 60 * 5;
  let timerId;
  let stopId
  let isRunning = false;
  let show_time = document.getElementById('show_time');

  function countDown(){
    timerId = setTimeout(function(){
      timeLeft = timeToCountDown - (Date.now() - startTime);

      if(timeLeft < 0){
        isRunning = false;
        clearTimeout(timerId);
        timeLeft = 0;
        timeToCountDown = 0;
        updateTimer(timeLeft);
        console.log("音楽ストップ");
        location.href="/musics/index";
        return;
      }
      updateTimer(timeLeft)
      countDown();
    },10);
  }

  function updateTimer(t){
    let d = new Date(t);
    let m = d.getMinutes();
    let s = d.getSeconds();
    m = ('0' + m).slice(-2);
    s = ('0' + s).slice(-2);
    let timerString = m + ":" + s;
    timer.textContent = timerString;
    document.title = timerString;
  }

  function timer_start(){
    if (isRunning === false){
      isRunning = true;
      startTime = Date.now();
      countDown();
    }else{
      isRunning = false;
      timeToCountDown = timeLeft;
      clearTimeout(timerId);
    }
    setTimeout(function(){
      audio.play();
    }, (timeToCountDown - 6000))
  }

  window.onload = timer_start(); 
  console.log("タイマースタート");
  window.addEventListener('popstate', function (e) {
    clearTimeout(timerId);
  });
  $(document).ready(function () {
    let view_box = $('.img_avatar');

    $(".file").on('change', function(){
      let fileprop = $(this).prop('files')[0],
      find_img = $(this).next('img'),
      fileRdr = new FileReader();

      if(find_img.length){
        find_img.nextAll().remove();
        find_img.remove();
      }

      let img = '<img width="100" alt="" class="img_view"><a href="#" class="img_del">プレビューを削除する</a>';
      view_box.append(img);

      fileRdr.onload = function() {    
        view_box.find('img').attr('src', fileRdr.result);
        img_del(view_box); 
      }

      fileRdr.readAsDataURL(fileprop);  

      if($(".img_view").length){
        $(".file").hide();
      }

      $(".your_preview").show();
    });

    function img_del(target){
      target.find("a.img_del").on('click',function(){
        $(this).parent().find('input[type=file]').val('');
        $(this).parent().find('.img_view, br').remove();
        $(this).remove();
        $("#post_post_image").val("");
        $(".file").show();
        $(".your_preview").hide();

        return false;
      });
    }  
  });
});
</script>