config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { 
     omniauth_callbacks: 'users/omniauth_callbacks',
     registrations: "users/registrations"
  }
  root to: "tops#index"

  get 'musics/index'
  post 'musics/search'
  get "musics/play"
  get "musics/rest"
  get "musics/history"
  get "musics/how"

  resources :users
  resources :posts
  resources :music_histories, only: %i[create]
  resources :post_favorites, only: %i[create destroy]

  namespace :admin do
    resources :users
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Pacifico" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Orbitron" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css" integrity="sha384-oS3vJWv+0UjzBfQzYUhtDYW+Pj2yciDJxpsK1OYPAYjqT085Qq/1cq5FLXAZQ7Ay" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css"/>
    <script type="text/javascript" src="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= favicon_link_tag('favicon.ico') %>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="/musics/index" data-turbolinks="false"></a>
      <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#Navber" aria-controls="Navber" aria-expanded="false" aria-label="ナビゲーションの切替">
        <span class="navbar-toggler-icon"></span>
      </button>
      <% if user_signed_in? %>
      <div class="collapse navbar-collapse" id="Navber">
        <ul class="navbar-nav nav-fill w-100 nav-justified">
          <li class="nav-item">
            <%= link_to "トップ", musics_index_path ,class: "nav-link", data: {"turbolinks" => false} %>
          </li>
          <li class="nav-item dropdown">
            <a href="#" class="nav-link dropdown-toggle" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <%= current_user.name %>さんのアカウント情報
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <%= link_to "プロフィール", user_path(current_user.id),class: "dropdown-item", data: {"turbolinks" => false}  %>
              <div class="dropdown-divider"></div>
              <%= link_to "ログアウト",  destroy_user_session_path, method: :delete, class: "dropdown-item", data: {confirm: "ログアウトしますか？"} %>
            </div>
          </li>
          <li class="nav-item">
            <%= link_to "再生履歴",  musics_history_path, class: "nav-link", data: {"turbolinks" => false}  %>
          </li>
          <li class="nav-item">
            <%= link_to "掲示板",  posts_path, class: "nav-link", data: {"turbolinks" => false}  %>
          </li>
          <li class="nav-item">
            <%= link_to "使い方", musics_how_path, class: "nav-link", data: {"turbolinks" => false}  %> 
          </li>
      <% end %>
          <% if current_user.try(:admin) %>
            <li class="nav-item dropdown">
              <a href="#" class="nav-link dropdown-toggle" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                管理者メニュー
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <%= link_to "ユーザー一覧",  admin_users_path, class: "dropdown-item" %>
                <%= link_to "ユーザー新規登録",   new_admin_user_path, class: "dropdown-item" %>
              </div>
            </li>
          <% end %>
        </ul>
      </div>
    </nav>
    <div class="container">
      <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %> fadeOut_alert"><%= message %></div>
      <% end %>
      <%= yield %>
    </div>
    <div class="container-fluid">
      <footer class="footer">
        <p>Powered by Aguru Itabashi</p>
      </footer>
    </div>

    <div id="back-to-top" style="position:fixed;right:25px;bottom:5px">
      <a href="#"><i class="fas fa-arrow-alt-circle-up fa-5x"></i></a>
    </div>

    <script type="text/javascript">
      document.addEventListener("turbolinks:load", function(){
        setTimeout("$('.fadeOut_alert').fadeOut('slow')", 3000) 
        $(function(){
          $("#back-to-top").hide();
          $(window).scroll(function(){
            $('#pos').text($(this).scrollTop());
            if ($(this).scrollTop() > 60){
              $("#back-to-top").fadeIn();
            }else{
              $('#back-to-top').fadeOut();
            }
          });
          $('#back-to-top a').click(function() {
            $('html, body').animate({
              scrollTop:0
            }, 800);
            return false;
          });
        });
      });
    </script>
  </body>
</html>